# Shamelessly ripped from plv8 repo
before_install:
  - psql --version
  - python --version
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove libpq5 libpq-dev postgresql postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - wget --no-check-certificate  --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-common
  - sudo sh -c "echo create_main_cluster = false >> /etc/postgresql-common/createcluster.conf"
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION postgresql-contrib-$PGVERSION
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libc6-dev-i386 libc++-dev python3-dev python-dev postgresql-plpython3-${PGVERSION}
  - sudo apt-get install postgresql-plpython-${PGVERSION} || true
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/python/${TRAVIS_PYTHON_VERSION}/lib/
  - mkdir /tmp/pgdata
  - /usr/lib/postgresql/${PGVERSION}/bin/initdb -A trust -D /tmp/pgdata
  - echo "unix_socket_directories='/tmp/'" >> /tmp/pgdata/postgresql.conf
  - /usr/lib/postgresql/${PGVERSION}/bin/pg_ctl -D /tmp/pgdata start

install:
  - python -m pip install --upgrade psycopg2 setuptools sqlalchemy

before_script:
  - g++ -v
  - gcc -v

python:
  - 3.7
  - 3.8
  - 3.9

env:
  matrix:
    - PGVERSION=10
    - PGVERSION=11
    - PGVERSION=12
    - PGVERSION=13

language: python
compiler:
  - gcc

sudo: required
dist: xenial

script:
  - which python
  - export PYTHON_CONFIG=/opt/python/${TRAVIS_PYTHON_VERSION}/bin/python-config
  - export PYTHON_OVERRIDE=/opt/python/${TRAVIS_PYTHON_VERSION}/bin/python
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/python/${TRAVIS_PYTHON_VERSION}/lib/
  - export PG_CONFIG=/usr/lib/postgresql/${PGVERSION}/bin/pg_config
  - export PGHOST=/tmp/
  - make && sudo make install
  - python -m pip install .
  - make installcheck

after_script:
  - cat regression.diffs || true
  - cat regression.out || true
